import Head from "next/head";
import { getSession, useSession, signOut } from "next-auth/react";
import Header from "../components/Header";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar"
import Feed from "../components/Feed"
import Widgets from "../components/Widgets"
import { db } from "@/firebase";

export default function Home({posts}) {
  const { data: session } = useSession()
  
  if (!session) {
    return <Login />
  }

   else{
    return (
      <div className="h-screen bg-gray-100 overflow-hidden">
        <Head>
          <title>Facebook</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className="flex">
          {/* sidebar */}
          <Sidebar />
          {/* feed */}
          <Feed />
          {/* widgets */}
          <Widgets />
        </main>
      </div>
    );
  }
}



export async function getServerSideProps(context) {
  const session = await getSession(context);

  const posts = await db.collection("posts").orderBy("timestamp", "desc").get();

   const docs = posts.docs.map(post => ({
    id: post.id,
    ...post.data(),
    timeStamp: null
   }) )
  return {
    props: {
      session,
      posts: docs
    },
  };
}
